---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intruder
  labels:
    app.kubernetes.io/part-of: mallory-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: intruder-token
  annotations:
    kubernetes.io/service-account.name: intruder
type: kubernetes.io/service-account-token
# Get token
# kubectl get secrets intruder-token -o jsonpath='{.data.token}' | base64 -d
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intruder-sa
  labels:
    app.kubernetes.io/part-of: mallory-operator
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: intruder
    namespace: default