apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-privileged-pod
spec:
  intruder:
    username: system:serviceaccount:default:intruder
  rule: CreatePrivilegedPod
  operations:
  - id: privileged-pod
    verb: create
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        name: privileged-pod
      spec:
        containers:
        - name: web
          image: nginx
          securityContext:
            privileged: true
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
      


