apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-hostnetwork-pod
spec:
  intruder:
    username: system:serviceaccount:default:intruder
  rule: CreateHostNetworkPod
  operations:
  - id: hostnetwork-pod
    verb: create
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        name: hostnetwork-pod
      spec:
        hostNetwork: true
        containers:
        - name: web
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
      


