apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-vanilla-sa
spec:
  intruder:
    serviceAccount: intruder
  operations:
  - id: vanilla-sa
    verb: create
    resource:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: vanilla-sa
        labels:
          app.kubernetes.io/part-of: mallory-operator
          mallory/rule: K8s-Serviceaccount-Created

  - id: vanilla-role
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: vanilla-role
        labels:
          app.kubernetes.io/part-of: mallory-operator
          falco.rules: K8s-Role-Clusterrole-Created
      rules:
      - apiGroups:
          - ""
        resources:
          - "pods"
        verbs:
          - list

  - id: vanilla-role-binding
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: vanilla-role-binding
        labels:
          app.kubernetes.io/part-of: mallory-operator
          mallory/rule: K8s-Role-Clusterrolebinding-Created
      roleRef:
        kind: Role
        name: vanilla-role
        apiGroup: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: vanilla-service-account