apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-root-user-pod
spec:
  intruder:
    username: intruder
    groups: 
     - intruder
  rule: CreatePodWithHostPort
  operations:
  - id: root-user-pod
    verb: create
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        name: root-user-pod
      spec:
        containers:
        - name: web
          image: nginx
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
      


