apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-sensitive-mount-deployment
spec:
  intruder:
    serviceAccount: intruder
  operations:
  - id: sensitive-mount-deployment
    verb: create
    resource:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sensitive-mount-deployment
        app.kubernetes.io/part-of: mallory-operator
        mallory/rule: Sensitive-Mount-Deployment-Created
      spec:
        selector:
          matchLabels:
            app: sensitive-mount-deployment
        template:
          metadata:
            labels:
              app: sensitive-mount-deployment
              app.kubernetes.io/part-of: mallory-operator
          spec:
            containers:
            - name: web
              image: nginx
              resources:
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              ports:
              - containerPort: 80
              volumeMounts:
              - mountPath: /host/etc
                name: etc
            volumes:
            - name: etc
              hostPath:
                path: /etc
      


