apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-suspicious-sa
spec:
  intruder:
    username: system:serviceaccount:default:intruder
  operations:
  - id: suspicious-sa
    verb: create
    resource:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: suspicious-sa

  - id: suspicious-role
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: suspicious-role
      rules:
      - apiGroups:
          - ""
        resources:
          - "pods"
        verbs:
          - list

  - id: suspicious-role-binding
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: suspicious-role-binding
      roleRef:
        kind: Role
        name: suspicious-role
        apiGroup: rbac.authorization.k8s.io
      subjects:
        - kind: ServiceAccount
          name: suspicious-sa