apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-role-with-write-privileges
spec:
  intruder:
    serviceAccount: intruder
  operations:
  - id: write-privileges-role
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: write-privileges-role
        labels:
          app.kubernetes.io/part-of: mallory-operator
          mallory/rule: Role-With-Write-Privileges-Created
      rules:
      - apiGroups:
          - ""
        resources:
          - "pods"
        verbs:
          - create