apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-role-with-exec
spec:
  intruder:
    username: intruder
  operations:
  - id: pod-exec-role
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: pod-exec-role
        labels:
          app.kubernetes.io/part-of: mallory-operator
          mallory/rule: Role-With-Pod-Exec-Created
      rules:
      - apiGroups:
          - ""
        resources:
          - "pods/exec"
        verbs:
          - get