apiVersion: mallory.io/v1
kind: Event
metadata:
  name: create-role-with-write-privileges
spec:
  intruder:
    username: system:serviceaccount:default:intruder
  operations:
  - id: write-privileges-role
    verb: create
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: write-privileges-role
      rules:
      - apiGroups:
          - ""
        resources:
          - "pods"
        verbs:
          - create