apiVersion: mallory.io/v1
kind: Event
metadata:
  name: dns-recon
spec:
  intruder:
    username: system:serviceaccount:default:intruder
  operations:
  - id: roles
    verb: create
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        name: dns-recon
      spec:
        containers:
        - name: intruder
          image: explabs/mallory-intruder
          args: 
           - "k8spider all"
