apiVersion: mallory.io/v1
kind: Event
metadata:
  name: list-roles
spec:
  intruder:
    username: intruder
  operations:
  - id: roles
    verb: list
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role