apiVersion: mallory.io/v1
kind: Event
metadata:
  name: list-cluster-roles
spec:
  intruder:
    user: 
      name: intruder
      groups: 
        - intruder
  operations:
  - id: cluster-roles
    verb: list
    resource:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole