apiVersion: mallory.io/v1
kind: Event
metadata:
  name: logs-etcd
spec:
  intruder:
    user: 
      name: intruder
      groups: 
        - intruder
  operations:
  - id: logs-etcd
    verb: logs
    resource:
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          component: etcd
        namespace: kube-system
